let foo a b c = decl
                let a =3;
                let b =4;
                let c =5 
                lced begin
                     doh(5,4);
                     blah(12,13);
                     a+b+bar(1,1)
                     end  


let bar d e = decl
              let a = 3;
              let b = 2 
              lced     
              begin
                      b+a+d+e
              end 

let doh g e = decl lced begin g+e end  
let blah l m = decl lced begin l-m+l*2 end
