let foo a b c = decl
                let a =3;
                let b =4;
                let c =5 
                lced begin
                     doh(3+1,4);
                     blah(12,13);
                     if 1 && 1 then a+b-bar(1,1) else 5
                     end  


let bar d e = decl
              let a = 3;
              let b = 2 
              lced     
              begin
                   if 1 then   
                   b+a+d+e
                   else 
                   d+d+d+d
              end 

let doh g e = decl lced begin g+e end  
let blah l m = decl lced begin l-m+l*2 end
